### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 2

### ISSUE THREAD

**Issue by oswetto** [katjas/PDFrenderer#31]
PDF: http://www.pdf995.com/samples/pdf.pdf

Hello i recompile this example https://github.com/clintel/PDFRenderer/blob/master/demos/viewer/com/sun/pdfview/PDFViewer.java with your fork, when i open PDF file with i recive this error

java.lang.ArrayIndexOutOfBoundsException: 2
	at com.sun.pdfview.PDFDestination.getDestination(PDFDestination.java:128)
	at com.sun.pdfview.PDFFile.getOutline(PDFFile.java:1489)
	at com.sun.pdfview.PDFViewer.openPDFByteBuffer(PDFViewer.java:777)
	at com.sun.pdfview.PDFViewer.openFile(PDFViewer.java:681)
	at com.sun.pdfview.PDFViewer.doOpen(PDFViewer.java:836)
	at com.sun.pdfview.PDFViewer$1.actionPerformed(PDFViewer.java:157)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by katjas** [comment]
Hi there,

are you sure you have the latest code? I can't reproduce the exception with your example PDF.

Kind regards,
Katja

**Comment by oswetto** [comment]
Hi,
yes i have last version of code. Only pdf with outline have this error. In your test you display outline?

In PDFViewer is called outline method curFile.getOutline(). The method try to create an action from a destination and call PDFDestination.getDestination(pdfObj, getRoot()). The pdfobject array have only position 0(PDFObject) and 1(type object) and in getDestination is aspected posistion  2 for setting top: dest.setTop(destArray[2].getFloatValue()). Type is "FitH". I suggest to set default value a 0.0f if is not present in array
