### ISSUE TITLE
Error in CCITTFaxDecoder

### ISSUE THREAD

**Issue by Okapist** [katjas/PDFrenderer#34]
With these pdf file 
https://drive.google.com/file/d/0Byw-cYW1T3D-cUR5WVR4NWkxWEE/view?usp=sharing

java.lang.RuntimeException: Invalid code encountered.
	at com.sun.pdfview.decode.CCITTFaxDecoder.decodeNextScanline(CCITTFaxDecoder.java:703)
	at com.sun.pdfview.decode.CCITTFaxDecoder.decodeT41D(CCITTFaxDecoder.java:820)
	at com.sun.pdfview.decode.CCITTFaxDecode.decode(CCITTFaxDecode.java:51)
	at com.sun.pdfview.decode.CCITTFaxDecode.decode(CCITTFaxDecode.java:17)
	at com.sun.pdfview.decode.PDFDecoder.decodeStream(PDFDecoder.java:103)
	at com.sun.pdfview.PDFObject.decodeStream(PDFObject.java:331)
	at com.sun.pdfview.PDFObject.getStream(PDFObject.java:263)
	at com.sun.pdfview.PDFObject.getStream(PDFObject.java:257)
	at com.sun.pdfview.PDFImage.getImage(PDFImage.java:225)
	at com.sun.pdfview.PDFRenderer.drawImage(PDFRenderer.java:273)
	at com.sun.pdfview.PDFImageCmd.execute(PDFPage.java:643)
	at com.sun.pdfview.PDFRenderer.iterate(PDFRenderer.java:570)
	at com.sun.pdfview.BaseWatchable.run(BaseWatchable.java:101)
	at com.sun.pdfview.BaseWatchable.execute(BaseWatchable.java:263)
	at com.sun.pdfview.BaseWatchable.go(BaseWatchable.java:197)
	at com.sun.pdfview.PDFPage.getImage(PDFPage.java:228)

**Comment by katjas** [comment]
Hi there,
sorry but I can't reproduce the exception with the file you provided. Can you retest it with the latest PDF renderer code?
Kind regards,.
Katja
