### ISSUE TITLE
Image not rendered: error "PDFParseException: Unsupported shader type: 7" in the console

### ISSUE THREAD

**Issue by alarregoity-inflexsys** [katjas/PDFrenderer#38]
Hello

With the attached PDF, that contains a logo, I get the following error
com.sun.pdfview.PDFParseException: Unsupported shader type: 7
	at com.sun.pdfview.pattern.PDFShader.getShader(PDFShader.java:139)
	at com.sun.pdfview.PDFParser.doShader(PDFParser.java:1231)
	at com.sun.pdfview.PDFParser.iterate(PDFParser.java:670)
	at com.sun.pdfview.BaseWatchable.run(BaseWatchable.java:104)
	at java.lang.Thread.run(Unknown Source)
in the console log, 

and the logo is not displayed in the result image.

[BA.pdf](https://github.com/katjas/PDFrenderer/files/70066/BA.pdf)

[ba](https://cloud.githubusercontent.com/assets/16403476/11962984/1ccfde52-a8e4-11e5-8173-3aaaf69bdcb5.jpg)

Armand Larregoity

**Comment by katjas** [comment]
Hello Armand,

thanks a lot for providing the patch, I have now merged it inot my branch.

Kind regards,
Katja
